dataset/batch.py
fix unexpected behavior in _assemble_component when results items has different shape but equal first dimension 
e.g., np.array([np.zeros((2, 2)), np.zeros((2,3))], dtype=object) fails, 
but np.array([np.zeros((2, 2)), np.zeros((3,3))], dtype=object) works fine.
=> fix _assemble_component

batchflow/config.py, batchflow/models/base.py
I have found 96 usages of method get in the batchflow repository. Some of them were modified after method get signature changing, but it was not necessary, and moreover, it was a mistake. So I rolled that changes back. And finally, I've found no usages of method get(...) which were depended on the order of unnamed arguments.
=> Edit the order of arguments in the Config class get-method

batchflow/models/tf/__init__.py, batchflow/models/tf/densenet.py, batchflow/models/tf/encoder_decoder.py, batchflow/models/tf/resnet.py, batchflow/tests/encoder_decoder_test.py
Modified `EncoderDecoder` model in order to:
- add ability to create encoder from individual blocks (e.g. `DenseNet.block`)
- same for embedding and decoder: now we can create them from individual blocks
- add parameter to control skip connections between corresponding encodings/decodings (`UNet`-like)
Also, arguments for upsampling layers are moved to separate key in order to prevent collisions; same for downsampling layers (when encoder is created from blocks). 
Changed order of layers in body of `DenseNet`: from `block-transition-block-transition-block-block` to `block-block-transition-block-transition-block` in order to stay consistent with `ResNet`. Added `make_encoder` method.
In `make_encoder` method of `ResNet` added error handling: otherwise error-messages are very confusing. …
=> Encoder decoder

batchflow/models/tf/base.py
Almost always we want to use `batch_size` big enough, so computed gradients are good estimates of true gradients. Unfortunately, that is often can not be done due to memory limitations of our hardware. 
Microbatching allows to sequentially compute (and accumulate) gradients from smaller pieces of data (namely, `microbatches`), and after enough iterations apply them at once.
There are three ways to use this feature:
- `microbatch` option in the `model_config`. Provided an integer value, it would make so that every `Batch` is split into even parts of that length. Example:
```
model_config = {'microbatch': 16}
train_pipeline = ...
train_batch = train_pipeline.next_batch(64, ...)
```
- `microbatch` option in the `model_config`. It can be either integer, True or pretty much anything else that …
=> TFModel: microbatching

batchflow/models/tf/base.py
This PR:
1) fixes problem with too many tensors matching search pattern in `_check_tensor` by using regular expressions for search;
2) changes structure of `_check_tensor` to provide more correct error messaging.
=> Fix _check_tensor

batchflow/models/tf/__init__.py, batchflow/models/tf/base.py, batchflow/models/tf/deeplab.py, batchflow/models/tf/encoder_decoder.py, batchflow/models/tf/layers/__init__.py, batchflow/models/tf/layers/conv.py, batchflow/models/tf/layers/pyramid.py, batchflow/models/tf/xception.py, batchflow/tests/encoder_decoder_test.py
This PR proposes following additions:
1. Change `ASPP` module in order to make it compatible with dynamic shapes. Note that building model with dynamic `ASPP` is slower, but there is no difference at train time.
2. Add [`Xception`](https://arxiv.org/pdf/1610.02357.pdf) model architecture: authors make case for heavy usage of `depthwise_conv`-`batchnorm`-`pointwise_conv` blocks. Note that modifications, pointed out in [this](http://presentations.cocodataset.org/COCO17-Detect-MSRA.pdf) paper, are applied, as well as modifications from this [implementation.](https://github.com/tensorflow/models/blob/58a3de6c68639c3eac95f7c84089f320d32a85bb/research/deeplab/core/xception.py)
3. Add [`DeepLab`](https://arxiv.org/pdf/1802.02611.pdf) model architecture: this one uses `Xception` as its backbone, …
=> DeepLab v3+

batchflow/models/torch/base.py
From torch.optim.lr_scheduler the following decay algorithms have been implemented:
* ExponentialLR
* LambdaLR
* StepLR
* MultiStepLR
* CosineAnnealingLR
* CyclicLR
Moreover new config parameter with name ```n_iters``` were introduced. This parameter should contain the number of iterations in one epoch.
Thus, simple config with decay scheduler can be written this way:
```python
config = {
...
'n_iters': 4,
'decay': ('exp'),
...
}
```
=> Torch decay

batchflow/models/tf/encoder_decoder.py, batchflow/models/tf/layers/layer.py
This PR proposes to:
- make order of operations configurable in both `encoder` and `decoder`: you can either process tensor via chosen `block` and then change its spatial resolution with `downsampling`/`upsampling`, or vice versa
- `skip` parameter of `decoder/blocks` can now be a dictionary of parameters, that are passed to `combine` function
- now `add_as_function` decorator is smart enough to pass `training` tensor only when needed
=> Encoder_decoder improvements

batchflow/opensets/__init__.py, batchflow/opensets/pascal.py
This PR proposes to add `PascalVOC` openset.
By now it processes Segmentation and Classification tasks. Each task is presented by the specific class, i.e `PascalSegmentation` for Segmentation task etc. 
The total list of tasks:
1. Classification
2. Detection
3. Segmentation
4. Action Classification Task
5. Boxless Action Classification
6. Person Layout
=> PascalVOC openset

batchflow/dsindex.py, batchflow/tests/filesindex_test.py
`os.path.split` raises different type of excpetions on python 3.7 and 3.5.
=> Add more exception types

batchflow/tests/regression_metrics_test.py
Avoid `numpy` raising warnings in `regression_metrics_tests.py`  since the cases, when the division by zero is encounted,  is explicitly processed in test functions.
=> Regrmetr generate warnings

batchflow/models/tf/base.py
This PR proposes to add method to configure config combining step of `TFModel` building. This mainly helps `PyDEns` library, but can also be used in other models
=> Combine configs

batchflow/models/tf/base.py, batchflow/models/tf/resnet.py, batchflow/models/torch/base.py, batchflow/models/torch/resnet.py
* This PR fixes bugs carefully placed in ResNet architectures in #434. 
* Also, it changes the way `_add_output_identity` handles its argument `name`: this argument is `None`, so upon concatenation with string argument `attr_prefix` it caused an error. This PR suggests to replace  `None` with empty string right before concatenation.
=> Fix ResNet models

batchflow/research/__init__.py, batchflow/research/named_expr.py
Add ResearchExperimentPath named expression to use the current experiment path in callable, for example, to dump models.
=> Add ResearchExperimentPath

batchflow/base.py, batchflow/batch.py, batchflow/components.py, examples/tutorials/01_batch_operations.ipynb
All except one are docstrings edits.
The one in code removes `Batch.load()` unnecessary `str->tuple` conversion, since it doesn't really affect `setdiff1d()` behaviour and the following `add_components()` does the same conversion.
This PR was originally aimed at fixing failing `01_batch_operations.ipynb` tutorial, but this fix is omiited now since there was a more complex one proposed. It requires more work and will be applied later.
=> Few simple fixes

batchflow/batch_image.py
Since there is an implicit type conversion in `ImagesBatch._multiply_` when applied to instance of `PIL.Image`, this simple warning will save time for those, who lose images data using something like `multiply(1/255, preserve_type=False)` in pipelines.
=> Add warning to ImagesBatch._multiply_

batchflow/model_dir.py
Since models are stored as a dict, iterating through self.models returned keys,
which are of str type. The subsequent application of reset() function to them
naturally caused an error. Iterating through values resolves the problem.
=> Fix ModelDirectory.reset

batchflow/research/__init__.py, batchflow/research/logger.py, batchflow/research/research.py
This PR:
- fixes a bug (when function receives non-empty `kwargs`, it crashes due to wrong `isinstance` call);
- generalizes args parsing — following calls are possible now:
- `add_logger('basic')`
- `add_logger('tg', token=token, id=id)`
- `add_logger((CustomLogger, {'arg': value}))`
- `add_logger(['basic', 'print'])`
- `add_logger(['basic', ('tg', {'token': token, 'id': id}), (CustomLogger, {'arg': value})])`
=> Modify Research.add_logger

batchflow/models/torch/layers/core.py
issubclass wants its first argument to be class, otherwise it raises an error
=> fix activation __init__ for callables and str

batchflow/batch.py, batchflow/utils.py
This PR removes random colour choice in `show_research`. This ensures consistent colour coding in successive plots using same data.
This PR also introduces another option to select colours for plots by providing a mathplotlib colormap name
=> remove randomization in show_research

batchflow/models/tf/__init__.py, batchflow/models/tf/base.py, batchflow/models/tf/encoder_decoder.py, batchflow/models/tf/fcn.py, batchflow/models/tf/inception_base.py, batchflow/models/tf/inception_resnet_v2.py, batchflow/models/tf/inception_v1.py, batchflow/models/tf/inception_v3.py, batchflow/models/tf/inception_v4.py, batchflow/models/tf/layers/__init__.py, batchflow/models/tf/layers/conv.py, batchflow/models/tf/layers/conv_block.py, batchflow/models/tf/layers/core.py, batchflow/models/tf/layers/drop_block.py, batchflow/models/tf/layers/pooling.py, batchflow/models/tf/layers/pyramid.py, batchflow/models/tf/layers/resize.py, batchflow/models/tf/mobilenet.py, batchflow/models/tf/refinenet.py, batchflow/models/tf/resnet.py, batchflow/models/tf/squeezenet.py, batchflow/models/tf/utils.py, batchflow/models/tf/vgg.py, batchflow/models/tf/xception.py, batchflow/tests/notebooks/tfmodel_test.ipynb, batchflow/tests/tf_models_compile_test.py
This PR proposes to:
- Make `ConvBlock` able to chain multiple layers, just like `Torch` version can
- Simplify logic of letter parsing, as well as adding capability of using `R` letter as separate `Branch` with complex parameters
- Swap all arguments inside calls to `conv_block` to keyword ones
- Add `squeeze-and-excitation` versions of `ResNet`
- Re-check all the tests of model compilation
- Add various attention modules: some of them are available through `S` (stands for self-attention) letter, some of them are mods of `Combine`
=> TFModel improvements

batchflow/models/torch/encoder_decoder.py, batchflow/models/torch/layers/__init__.py, batchflow/models/torch/layers/modules.py, batchflow/named_expr.py
This PR proposes to:
- add a kernel-sharing atrous pyramid
- make `EncoderDecoder` compatible with dynamically generated shapes
- fix `NamedExpression` recursive evaluation
=> Torch improvements

batchflow/research/distributor.py, batchflow/research/named_expr.py, batchflow/research/research.py, batchflow/research/workers.py
The previous default value for timeout (5 minutes) in Research doesn't allow to execute massive tasks in callables.
Now by default timeout is None.
RC (ResearchConfig) named expression can be used without the specification of the executable unit.
=> Default timeout for Research is None; RC can be without name

.github/workflows/status.yml, batchflow/batch.py, batchflow/batch_image.py, batchflow/dataset.py, batchflow/decorators.py, batchflow/dsindex.py, batchflow/models/sklearn.py, batchflow/models/tf/linknet.py, batchflow/models/tf/vnet.py, batchflow/models/torch/base.py, batchflow/models/torch/optimizers/radam.py, batchflow/opensets/base.py, batchflow/opensets/coco.py, batchflow/research/executable.py, batchflow/tests/assemble_test.py, batchflow/tests/named_expr_test.py
This PR fixes pylint output in the latest docker image analysiscenter1/ds-py3. 
A lot of `missing-function-docstring` and `abstract-method` warnings happened in `batchflow/models/torch` folder we cant fix, because they occur on the torch side. They are fixing [this](https://github.com/pytorch/pytorch/issues/42305) and [this](https://github.com/pytorch/pytorch/issues/43057). 
So we can:
1.  Close eyes on this warnings.
2.  Temporary set additional restrictions for pylint for `torch` folder only like its currently done. 
@roman-kh
=> Fix pylint

batchflow/pipeline.py
Previously, `load_model` was executed each iteration. Now only once.
=> Fix load model

batchflow/utils.py
Make colors consistent across different plots in research results
Before fix (Note different line colors for same configs):
after fix:
=> fix colors in show_research

batchflow/models/torch/blocks.py
layout parameter is removed from MBConvBlock, because it is not really used by people and non-default values are not properly working with current ConvBlock
=> remove layout parameter

batchflow/models/torch/base.py, batchflow/models/torch/layers/conv_block.py, codecov.yml
This PR proposes to split `TorchModel._fill_input` method, which formerly did the following:
- parsed positional and named arguments into model `inputs` and `targets`
- transfered them to `model.device`
into two methods: `parse_inputs` and `transfer_to_device`. That allows for finer control over when data is copied onto GPU, which is necessary to pass individual microbatches at a time (not the whole training batch).
It also allows for more options for passed data: now model can be trained with `np.ndarray`'s, `torch.Tensor`'s and `cupy.ndarray`'s.
=> Pass microbatches on device individually

batchflow/models/torch/base.py, batchflow/models/torch/visualization.py, batchflow/notifier.py
The main contribution of this PR is the conversion of predicted arrays back to `float32` precision, even with `amp` turned on
=> Fixes for torch model and notifier

batchflow/__init__.py, batchflow/utils_notebook.py
`run_notebook` allows to execute external `.ipynb` file and save the output as a separate notebook, as well as to convert it to HTML for convenience.
=> Add run_notebook function

batchflow/named_expr.py
`C.get` fails to retrieve the default value for named expression when pipeline config is empty.
This happens due to a call on line `528`, where keyword argument `default` is passed.
Since the default python `dict` takes no keyword arguments, such call leads to `TypeError`.
=> Fix default retrieval for `C`

batchflow/__init__.py, batchflow/named_expr.py, batchflow/tests/named_expr_test.py
This pool request provides:
* Named expression L that is aimed at working with batch components that contains a list of objects. Also, it provides to redirect calls of getitem/getattr/setitem/setattr into objects itself by writing:
* `L('comp').attr` or `L('comp')[item]` or even `L('comp').attr1.attr2[item1].attr3 ...` etc.
* Add some operators to named expression
=> L expression

batchflow/utils_notebook.py
In this PR:
- change requests to jupyter lab API to a newer version
- add `use_pylintrc` option to `pylint_notebook` function: this allows to use the BatchFlow pylint configuration in the linted notebook as well
=> Update notebook utils

batchflow/batch_image.py, batchflow/opensets/base.py, batchflow/opensets/cifar.py, batchflow/opensets/imagenette.py, batchflow/opensets/mnist.py, batchflow/opensets/pascal.py
- Fix `split_to_patches`
- Fix warnings like 
```
FutureWarning: The input object of type 'JpegImageFile' is an array-like implementing one of the corresponding protocols 
(`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced 
as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'JpegImageFile', 
or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
images = np.array([_extract(archive, file) for file in files], dtype=object)
```
=> Fix warning from opensets; Fix split_to_patches

batchflow/batch_image.py, batchflow/models/metrics/classify.py, batchflow/plotter/plot.py
Note, that there is a bug that show itself, when calling `train_model` action in corresponding pipeline. Since fixing this goes beyond the limits of current PR, the updated plot contents correspond to model predictions, that was not trained at all. Just re-run the notebook after fixing mentioned bug, and all the plots should come back together and relevant.
=> Use `plot` in tutorial notebook instead of outdated `plot_images`

batchflow/__init__.py
Building docs is failing due to the absence of __version__ attribute. Added another way of getting this attribute via parsing pyproject.toml file.
=> added another way of getting version(via pyproject file)

batchflow/tests/transforms_test.py, batchflow/utils_transforms.py
Make notation more clear: `q` usually stands for q-level (probability) but we use it as quantile values.
=> Rename `q` to `quantiles`

batchflow/sampler.py
This PR fixes the non-obvious bug when using `OrSampler`: the multiplication changes the sampler weight inplace which in some cases can be crucial.
**e.g.** `other_sampler = (1 & sampler_1)| (0 & sampler_2)` will change `sampler_1` and `sampler_2` weights
=> Add weighted sampler

batchflow/plotter/cmaps.py, pyproject.toml
Necessary for `matplotlib>=3.9.0` but also works for older versions (e.g. `3.7.5`)
Closes #746
=> Update for matplotlib

batchflow/models/torch/base.py
Add `ignore_attributes` to `save` method to avoid serialization issues for optimizer with the newest versions of pytorch and python
=> Fix save model
