- dataset/models/tf/layers/conv1d_tr.py
Add kwargs in conv1d_transpose
> add kwargs

- dataset/models/tf/tf_model.py
> add tensor functions

- dataset/models/keras/__init__.py
- dataset/models/keras/keras_model.py
1) Created subdir in dataset/models.
2) Added base class for keras models(KerasModel).
3) Added __init__.py for dataset/models/keras
> Keras model

- dataset/models/tf/base.py
- dataset/models/tf/linknet.py
data_format wasn't defined in num_channels
> fix data_format in num_channels; predicted_probA

- dataset/batch.py
- dataset/batch_image.py
- dataset/opensets/cifar.py
- dataset/opensets/mnist.py
1) opensets in `PIL`
2) target=`for` in `Imagesbatch` actions
3) bug fixes
> Quick fixes

- dataset/base.py
- dataset/dsindex.py
- dataset/opensets/base.py
- dataset/opensets/cifar.py
- dataset/opensets/mnist.py
- docs/intro/dataset.rst
- examples/tutorials/01_batch_operations.ipynb
- examples/tutorials/04_linear_models_example.ipynb
1. cv_split->split (really misleading).
2. [KFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html) class could be used for cv_split
P.S. I know that it is a Medvedev-style commit but it really bothers me
> cv_split to split

- dataset/batch.py
- dataset/batch_image.py
get_file_name supports ct_batch
add components before loading (to make possible to get new components in self[ix])
> Get file name

- batchflow/batch_image.py
Add transformations from PIL.ImageEnhance under single action `enhance_image`.
Remove `multiply_lightness` action.
> Add image augs

- batchflow/dsindex.py
- batchflow/pipeline.py
- batchflow/research/distributor.py
- batchflow/research/research.py
- docs/intro/research.rst
- examples/tutorials/08_research.ipynb
- examples/tutorials/10_cross_validation.ipynb
- Add custom `bar` for `.run`
- Rename `progress_bar` to `bar` in `Research`
> Progress bar

- batchflow/models/tf/base.py
Added option to use optimizer created for one `train_step` in another `train_step`. To do so, one can pass `use` key in config-dict, with value referencing name of `train_step` to get optimizer from:
```
{'train_steps': {'all': {'loss': 'ce', 'optimizer': 'Adam', 'scope': ''},
'body': {'loss': 'dice', 'optimizer': 'RMSProp', 'scope': 'body'}}
'custom': {'use': 'body', 'loss': 'ce', 'scope': 'head'}}
```
Note that it is still possible to use different loss/scope.
> Reuse optimizer

- batchflow/models/tf/base.py
To keep previous behaviour: return list if fetches is list, return value if fetches is string/tensor name
> Fix tf_model train 

- batchflow/models/tf/base.py
Remove excessive reset.
Rename json-related things to dill-related things.
> TFModel fixes

- batchflow/models/tf/base.py
This PR proposes to:
- move some of the `train` logic to separate functions: `_microbatch_train`, `_multi_train`, etc
- add capability to use microbatch on multiple devices
- make some small incremental changes like scope naming, op names, etc
> TFModel improvements

- batchflow/base.py
- batchflow/dsindex.py
- batchflow/named_expr.py
- batchflow/pipeline.py
Allows to dynamically update bar description
```
train_pipeline.run(16, n_iters=1000, bar='n',
bar_desc=W(V('current_loss').format('Loss is: {:7.7}')), )
```
> Bar description

- batchflow/tests/notebooks/torch_test.ipynb
.. and use `bar_desc` in testing pipelines
> Add torch tests

- batchflow/batch.py
- batchflow/pipeline.py
- batchflow/tests/apply_transform_test.py
- batchflow/tests/rebatch_test.py
> Rebatch test

- batchflow/models/tf/base.py
This PR proposes to add `scse_block` class method to TFModel.
> Introduce SCSE block

- batchflow/batch_image.py
- batchflow/opensets/__init__.py
- batchflow/opensets/imagenette.py
- batchflow/opensets/small_imagenet.py
This PR proposes to add `Imagenette` and `Imagewoof` opensets  and its versions to `batchflow/opensets`
> new_opensets

- batchflow/models/tf/encoder_decoder.py
- batchflow/models/tf/linknet.py
Linknet scheme is the same as in the article
> Linknet update

- batchflow/research/research.py
Fix `load_results` when `n_iters=None`
> Fix research

- batchflow/models/tf/encoder_decoder.py
- batchflow/models/tf/unet.py
- batchflow/tests/model_save_load_test.py
build_config for Unet to make default parameters
+ test fix
> Unet build config

- batchflow/models/tf/base.py
Contribution of this PR is two-fold:
- Make `loss` capable of working with functions that use more than two tensors to compute value of loss
- Slightly refactor `_make_loss` and `make_decay`
Note that this PR needs #420 to be merged beforehand to add documentation in better format.
> Change loss and decay

- batchflow/models/metrics/__init__.py
- batchflow/models/metrics/regression.py
- batchflow/pipeline.py
- batchflow/tests/regression_metrics_test.py
This PR proposes to add regression metrics and tests. 
No tests provided yet.
Metrics are compatible with multi output task i.e. when targets have shape `(n_samples, n_outputs)`. In this case aggregation among outputs is available.
> Regression metrics

- batchflow/tests/model_save_load_test.py
- batchflow/tests/torch_models_test.py
> fixed iss_449 + fixed torch_models_test

- batchflow/models/torch/base.py
- batchflow/models/torch/blocks.py
- batchflow/models/torch/encoder_decoder.py
- batchflow/models/torch/layers/__init__.py
- batchflow/models/torch/layers/conv_block.py
- batchflow/models/torch/layers/core.py
- batchflow/models/torch/layers/resize.py
- batchflow/models/torch/resnet.py
- batchflow/models/torch/unet.py
- batchflow/tests/notebooks/torch_test.ipynb
Changelist:
- Make `get_defaults` update dicts with `Config`-like functionality: only end leaves are updated
- `device`/`devices` are no longer saved, and `save`/`load` methods now use `dill` module for pickling
- EncoderDecoder now can use `base_model` class to create encoder
- `SideBlock` is renamed to `Branch`, and `R` now provides the same functionality as `B`
> Torch improvements

- batchflow/research/named_expr.py
- examples/tutorials/research/01_introduction_to_research.ipynb
- Fix bug in `REP`  (`unit.path` -> `unit.experiment_path`)
- Add `inner` parameter to REP (absolute or relative (with respect to Research folder) path to experiment path)
> Add `inner` parameter to REP

- .github/workflows/status.yml
- batchflow/__init__.py
- batchflow/named_expr.py
- batchflow/pipeline.py
- batchflow/tests/save_to_test.py
- batchflow/utils.py
> Universal save_to

- batchflow/models/tf/base.py
- batchflow/research/research.py
- batchflow/research/workers.py
Fix allocation of GPU:0 when visible devices are not specified.
NOTE: For `tensorflow>=1.15.0`, otherwise GPU:0 also will be allocated when model has `conv2d`
> Fix zero gpu allocation

- batchflow/notifier.py
More types for valid description in `Notifier`
> Fix Notifier description

- batchflow/models/torch/base.py
- batchflow/models/torch/losses/__init__.py
- batchflow/models/torch/losses/core.py
- batchflow/models/torch/losses/lovasz.py
- batchflow/models/torch/losses/multiclass.py
- batchflow/models/torch/losses/ssim.py
This PR adds:
- [`Lovasz softmax`](https://arxiv.org/abs/1705.08790) 
- [`SSIM as a loss` ](https://en.wikipedia.org/wiki/Structural_similarity)
- fixes microbatch and decay
> Pytorch losses

- batchflow/models/torch/base.py
- batchflow/models/torch/layers/conv_block.py
- batchflow/models/torch/visualization.py
This PR proposes to add visualizations of:
- intermediate activations
- intermediate layers
- model attention via [GradCam](https://arxiv.org/pdf/1610.02391.pdf)
> Pytorch visualizations

- batchflow/models/torch/unet.py
channels in original UNet are halved after upsampling
> fix unet channels after upsampling

- batchflow/exceptions.py
- batchflow/models/torch/base.py
- batchflow/models/torch/callbacks/__init__.py
- batchflow/models/torch/callbacks/base.py
- batchflow/models/torch/callbacks/plateau.py
- batchflow/pipeline.py
This PR proposes to add callbacks to the `TorchModel`:
- general interface `BaseCallback`: a class that implements a `on_iter_end` method
- `LogCallback`, `EarlyStopping`, `ReduceLROnPlateau`, as well as `PlateauCallback`, are already implemented
Currently, most of the docstrings are unfinished. I need feedback on functionality (and parameters) to make them clear and concise. Also, I am really unsatisfied with the implementation of the `on_plateau` condition in both `Pytorch` and `Keras`, and I am yet to be satisfied with the implementation of mine. Suggestions are welcome!
> Torch callbacks

- batchflow/models/torch/layers/modules.py
https://github.com/analysiscenter/batchflow/issues/561
> fixes in global pooling with bilinear interpolation

- .github/workflows/status.yml
- batchflow/models/tf/layers/core.py
- batchflow/models/tf/unet.py
- batchflow/models/torch/blocks.py
- batchflow/models/torch/encoder_decoder.py
- batchflow/models/torch/layers/attention.py
- batchflow/models/torch/layers/resize.py
- batchflow/models/torch/losses/core.py
- batchflow/models/torch/resnest.py
- batchflow/models/torch/resnet.py
- batchflow/models/torch/unet.py
- batchflow/models/torch/vgg.py
- batchflow/models/torch/visualization.py
- batchflow/models/torch/vnet.py
- batchflow/monitor.py
- batchflow/notifier.py
- batchflow/pipeline.py
- batchflow/research/domain.py
- pylintrc
This PR fixes pylint errors and fixes the used version, as well as:
- Add missing docstring for `Notifier`
- add `savepath` to `Monitors`
- make `short_repr` return string in `TorchModel`
> Fix pylint 

- batchflow/batch_image.py
Rewrote _sp_<func_name> definition to direct import function from scipy module.
ELastic transform work well now.
> bugs fix in elastic transform func

- batchflow/models/torch/base.py
> Replace deprecated method

- batchflow/pipeline.py
To do something like that:
```
ppl = (Dataset(1).p
.update(B('images'), np.random.normal(size=1))
.rebatch(batch_size=C('batch_size'), components='images')
.run_later(5)
)
ppl = ppl << Config({'batch_size': 3})
```
> Rebatch works with named expressions

- batchflow/named_expr.py
- batchflow/tests/named_expr_test.py
This pull request extends the functionality of L named expression. Now we can call a method from objects, via:
`L('comp').method(*args, **kwargs)`
> Add __call__ to L named expression

- batchflow/research/distributor.py
- batchflow/research/experiment.py
- batchflow/research/named_expr.py
- batchflow/research/research.py
- batchflow/tests/research_test.py
- add `save_output_dict'
- update research tests for `master`
- fix processing of the second chunk of tasks
- improve random generating
> Research imp

- batchflow/models/torch/base.py
- batchflow/notifier.py
- batchflow/tests/common_index_test.py
- batchflow/tests/conftest.py
- batchflow/tests/model_save_load_test.py
- batchflow/tests/test_loss_test.py
- batchflow/tests/torch_models_compile_test.py
- batchflow/tests/torch_models_test.py
- Fix outputs creation for loaded model
- Update tests
> Fix model loading

- batchflow/base.py
- batchflow/batch.py
- batchflow/batch_image.py
- batchflow/components.py
- batchflow/config.py
- batchflow/dataset.py
- batchflow/dsindex.py
- batchflow/model_dir.py
- batchflow/models/torch/base.py
- batchflow/models/torch/blocks/attention.py
- batchflow/models/torch/blocks/pyramid.py
- batchflow/models/torch/optimizers/radam.py
- batchflow/named_expr.py
- batchflow/once_pipeline.py
- batchflow/opensets/mnist.py
- batchflow/pipeline.py
- batchflow/research/domain.py
- batchflow/sampler.py
- batchflow/tests/common_index_test.py
- batchflow/tests/filesindex_test.py
- batchflow/tests/metrics_test.py
- batchflow/tests/regression_metrics_test.py
- batchflow/utils_random.py
- batchflow/variables.py
- examples/experiments/stochastic_depth/resnet_with_stochastic_depth.py
Why: https://pylint.pycqa.org/en/latest/user_guide/messages/convention/consider-using-f-string.html
How: https://github.com/ikamensh/flynt
> Convert all outdated formatted strings to f-strings

- batchflow/models/torch/blocks/__init__.py
- batchflow/models/torch/blocks/named_blocks.py
- batchflow/models/torch/layers/__init__.py
- batchflow/models/torch/layers/conv_complex.py
- batchflow/models/torch/layers/multilayer.py
implemented deformable conv v3
> deformable conv

- batchflow/models/torch/layers/combine.py
- batchflow/models/torch/utils.py
minor fix to force resize so that `center_crop` will receive correct `output_size` in form `(H, W)` not only in 2D case
> fixed 1d center_crop

- batchflow/plotter/plot.py
Make grid unvisible by default
> Fix grid visibility

- batchflow/monitor.py
- batchflow/plotter/plot.py
> Fix gpu monitor

- batchflow/plotter/plot.py
Updates in the `Plot`:
- Add detach modes (`True`, `False`, `'save'`) for running in daemon process
- Add `v_common` argument which affects `vmin` and `vmax` plotting arguments
> `plot` updates (`detach` mode, `v_common` arg)

- .github/workflows/test-install.yml
- README.md
- batchflow/decorators.py
> Test new pythons

- batchflow/models/torch/base.py
- batchflow/named_expr.py
- batchflow/notifier.py
This PR:
- adds a new `IF` named expression, which uses a `condition` to select outcome.
This greatly simplifies some of the named expressions, that we've used for selecting, say, model train mode or shapes (looking at you, `(I.current < 500) * 'train' + (I.current >=500) * 'eval'`)
- adds a way to use callbacks in `Notifier`.
Again, simplifies the interface: instead of subclassing the `Notifier` or `DummyBar` or `tqdm.standard` for adding an action (for example, logging to a custom state-recorder), one can use a simple function to do the same.
- grants a finer control over the model `init_weights` and `mode` parameter of `train/predict` methods.
The latter can be used for implementing custom schemes like `eval mode but with the dropout turned on`, which is somewhat cumbersome to …
> Improvements

- batchflow/models/torch/base.py
Actually use preserved attributes list without ignored attributes when saving the model
> Use proper serialization argument
